{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.952.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"student_activity_data\",\"student_data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "6cc0b829-8860-4203-bfe1-6e1c5657d07d",
        "fromColumn": "PARTICIPATION_DATE",
        "fromTable": "student_activity_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a2e0e96a-9df7-4a98-918a-6a0a42d49ce0"
      },
      {
        "name": "AutoDetected_349a4089-032f-461e-8561-ce5e5a1fb457",
        "fromColumn": "STUDENT_ID",
        "fromTable": "student_activity_data",
        "toColumn": "STUDENT_ID",
        "toTable": "student_data"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "student_activity_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ACTIVITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cca9412-bc8e-4a16-bcd9-0ca3fa5bce9d",
            "sourceColumn": "ACTIVITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "STUDENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51099619-ee7b-4c5d-8ac5-9c53a44d49c2",
            "sourceColumn": "STUDENT_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ACTIVITY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf6e7600-cd5f-4f45-86ee-4f7ca6553ac6",
            "sourceColumn": "ACTIVITY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "PARTICIPATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "984ea995-d409-472a-b414-ba56ac39c7d1",
            "sourceColumn": "PARTICIPATION_DATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a2e0e96a-9df7-4a98-918a-6a0a42d49ce0"
                },
                "isDefault": true,
                "relationship": "6cc0b829-8860-4203-bfe1-6e1c5657d07d"
              }
            ]
          },
          {
            "name": "HOURS_SPENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f3929ab-8020-47a4-b99c-f924d79cd42a",
            "sourceColumn": "HOURS_SPENT",
            "summarizeBy": "sum"
          },
          {
            "name": "ACTIVITY_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a272caa-1c20-45ae-95d8-0c2ffa2325c1",
            "sourceColumn": "ACTIVITY_TYPE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "042defc0-6eec-4775-9bbf-0664c1d78f49",
        "partitions": [
          {
            "name": "student_activity_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"H:\\Projects\\Data Services\\2024-2025\\PBI GitHub Integration\\student_activity_data.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ACTIVITY_ID\", type text}, {\"STUDENT_ID\", type text}, {\"ACTIVITY_NAME\", type text}, {\"PARTICIPATION_DATE\", type date}, {\"HOURS_SPENT\", Int64.Type}, {\"ACTIVITY_TYPE\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_531f52f7-e008-4907-abf9-c4bd36020275",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e4b2b96a-bf2e-406b-9e6f-388cea7dcf57",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ab5bad3a-ca53-4287-806b-463a51b45767",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7492966b-ddf1-4e78-a999-bdea37241fbb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c322de51-56cc-4510-a9af-88f4bfdfa334",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2e5f5947-73c7-4da3-aba5-eb717d9d2c8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "abe19f77-513c-4dd9-9293-7c45097cb607",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3355627d-1ec6-4d4f-bef2-82c97e45a959",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e7c5db61-a0eb-4c75-806a-1bb8b16d4447",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3854544f-c8f4-40b5-8d1d-2357be83ce8f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "23c5bef4-6c41-4389-af77-a938fbfc31df",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fb5d12bf-6d6a-4755-8dc4-d69f340cb04d",
                "ordinal": 3
              }
            ],
            "lineageTag": "2852bdd2-8082-4bed-8250-ad82a70f82a1"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a78fb778-01ed-438c-a5e0-dcc2f6582dd4",
        "partitions": [
          {
            "name": "DateTableTemplate_531f52f7-e008-4907-abf9-c4bd36020275",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a2e0e96a-9df7-4a98-918a-6a0a42d49ce0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "efbc9003-cc6e-4d1b-b14a-ee4edf5bafea",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81b6b48a-c51c-46c6-946e-0f7234b2af47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "19a52d55-a91e-4774-87a3-9174658f4bed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dec220b4-41ac-4c72-abf8-e31e1fe645c9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "df68c910-9ab3-4c6b-82cc-3293cce8d27d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d7c43920-78f4-4e27-b36a-2a8464285407",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0c162915-30d2-4243-99a3-5bf3ce188c4f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d12708b1-e14e-43b9-ade0-c5dff5e7ae9b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "dcde5407-35f5-4130-aaf2-d423cfc412c1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d9cc3815-2f64-4ce8-8307-9844c5bb8ff7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "93c41da0-1bd3-4f62-a4f6-4c5bafc312db",
                "ordinal": 3
              }
            ],
            "lineageTag": "46e59778-2a2c-48a5-ae42-7292f73917af"
          }
        ],
        "isHidden": true,
        "lineageTag": "cdcebbe9-44e3-415c-a3ae-ed077661f10d",
        "partitions": [
          {
            "name": "LocalDateTable_a2e0e96a-9df7-4a98-918a-6a0a42d49ce0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('student_activity_data'[PARTICIPATION_DATE])), 1, 1), Date(Year(MAX('student_activity_data'[PARTICIPATION_DATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "student_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "STUDENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a3f514c-4131-480f-ba37-557a8ee1fa8b",
            "sourceColumn": "STUDENT_ID",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a38a7eb0-4724-4641-b59b-d5c0822dd561",
            "sourceColumn": "LAST_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "FIRST_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9297a911-63a2-46bf-8251-c9b63b839473",
            "sourceColumn": "FIRST_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "ADMIT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a22958f-c900-442b-9425-daf595616a67",
            "sourceColumn": "ADMIT_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "ATHLETE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3679f6a5-5e59-44fd-9e06-41a8ed2a4721",
            "sourceColumn": "ATHLETE",
            "summarizeBy": "none"
          },
          {
            "name": "GENDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e3a0092-3109-4f34-95eb-5fbc09bb5f28",
            "sourceColumn": "GENDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2b0804f1-5096-4ade-9cc1-1a4395709114",
        "partitions": [
          {
            "name": "student_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"H:\\Projects\\Data Services\\2024-2025\\PBI GitHub Integration\\student_data.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"STUDENT_ID\", type text}, {\"LAST_NAME\", type text}, {\"FIRST_NAME\", type text}, {\"ADMIT_TYPE\", type text}, {\"ATHLETE\", type text}, {\"GENDER\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}