{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.952.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"student_data\",\"student_activity_data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_79da4b27-c22e-4e6b-993f-3dc9838f2d1f",
        "fromColumn": "STUDENT_ID",
        "fromTable": "student_activity_data",
        "toColumn": "STUDENT_ID",
        "toTable": "student_data"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "student_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "STUDENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e33326dd-09d9-408d-99c5-d6afa85e7482",
            "sourceColumn": "STUDENT_ID",
            "summarizeBy": "none"
          },
          {
            "name": "LAST_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "504a1d37-fce1-40c4-9b4b-bd228d8d30d1",
            "sourceColumn": "LAST_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "FIRST_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f77ef171-2925-4c0a-87b4-235ce3e37591",
            "sourceColumn": "FIRST_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "ADMIT_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4870a2ef-c2d9-4a88-9a73-9fbdea672c2e",
            "sourceColumn": "ADMIT_TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "ATHLETE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91904115-c128-4a3a-8f7b-d011dac37ae9",
            "sourceColumn": "ATHLETE",
            "summarizeBy": "none"
          },
          {
            "name": "GENDER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81b50a1e-ea7a-4295-8ef9-bf6288f21f48",
            "sourceColumn": "GENDER",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7c348334-af33-4a09-b5ab-427305dbbce2",
        "partitions": [
          {
            "name": "student_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1xi3U52HHejo1GkcsDYz75wQ-qaciJb7UFBssGBlBUN0/edit?gid=0#gid=0\"),",
                "    student_data_Table = Source{[name=\"student_data\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(student_data_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"STUDENT_ID\", type text}, {\"LAST_NAME\", type text}, {\"FIRST_NAME\", type text}, {\"ADMIT_TYPE\", type text}, {\"ATHLETE\", type text}, {\"GENDER\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "student_activity_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ACTIVITY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5935ed4e-1863-4cfe-b226-4e8ee7a4e62c",
            "sourceColumn": "ACTIVITY_ID",
            "summarizeBy": "none"
          },
          {
            "name": "STUDENT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "941fb50a-cca4-4c34-ae99-f09591ea0b90",
            "sourceColumn": "STUDENT_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ACTIVITY_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7976a3de-29f3-4b92-8202-821aa486ba1a",
            "sourceColumn": "ACTIVITY_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "PARTICIPATION_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ce97f49-5d72-418d-bf94-5fb856432f03",
            "sourceColumn": "PARTICIPATION_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "HOURS_SPENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80b5e72d-8a71-4644-b39f-18af5b1ff064",
            "sourceColumn": "HOURS_SPENT",
            "summarizeBy": "sum"
          },
          {
            "name": "ACTIVITY_TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faec168b-bf00-4793-ac4f-303d1f876883",
            "sourceColumn": "ACTIVITY_TYPE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e9c24814-1395-421a-8d03-c3ba132932b3",
        "partitions": [
          {
            "name": "student_activity_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1xi3U52HHejo1GkcsDYz75wQ-qaciJb7UFBssGBlBUN0/edit?gid=0#gid=0\"),",
                "    student_activity_data_Table = Source{[name=\"student_activity_data\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(student_activity_data_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ACTIVITY_ID\", type text}, {\"STUDENT_ID\", type text}, {\"ACTIVITY_NAME\", type text}, {\"PARTICIPATION_DATE\", type any}, {\"HOURS_SPENT\", Int64.Type}, {\"ACTIVITY_TYPE\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}